# Generated by Django 3.2.9 on 2021-11-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoId', models.CharField(max_length=50)),
                ('commentId', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=200)),
                ('likes', models.CharField(max_length=100)),
                ('dislikes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VideoReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoId', models.CharField(max_length=50)),
                ('commentId', models.CharField(max_length=50)),
                ('reply', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
