# Generated by Django 3.2.9 on 2021-11-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_auto_20211122_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocomment',
            name='commentId',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='videocomment',
            name='dislikes',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='videocomment',
            name='likes',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='videoreply',
            name='commentId',
            field=models.IntegerField(max_length=50),
        ),
    ]
