# Generated by Django 3.2.9 on 2021-11-23 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_auto_20211123_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocomment',
            name='commentId',
        ),
    ]
